### ISSUE TITLE
[Enhancement]: Linux ARM64 Release

### ISSUE THREAD

**Issue by defencedog** [0x90d/videoduplicatefinder#551] opened 2024-12-01 23:56 UTC
## Environment
 - OS: [e.g. Windows / Linux / MacOS ]
 - Linux

## Describe desired feature

Needed for ARM64 SBC (Rockchip)

**Comment by 0x90d** [comment] 2024-12-27 09:27
Dupe of #551

**Closed by 0x90d** 2024-12-27 09:27 UTC
Labels: enhancement
