### ISSUE TITLE
Inverted "Select Lowest Duration/Quality" selection with 3 or more duplicates

### ISSUE THREAD

**Issue by ibintcd** [0x90d/videoduplicatefinder#367] opened 2023-01-09 18:25 UTC
**Environment**
 - OS: Windows

**Describe the bug**
As [quoted](https://github.com/0x90d/videoduplicatefinder/issues/362#issuecomment-1375253291) by the owner of this repository in issue #362; the "Select Lowest Duration/Quality" option will go through these orders:

1. Lowest Duration
2. Lowest Resolution
3. Lowest FPS
4. Lowest Bitrate
 

However, if VDF has found 3 or more duplicates; the selection is inverted. More specifically, it selects everything that is **not** the lowest duration, resolution, fps or bitrate in that descending order. 

Two screenshot examples will visualize the issue more:
![20230109-215434_VDF GUI](https://user-images.githubusercontent.com/99754576/211375691-91d86077-efdd-4798-87fe-5d6ea7c2be55.png)
(apologies for the colour of the 4th video, thought it looked more purple but I was at an angle)

All videos have the same duration and FPS, however the red video has the lower resolution & bitrate, the former of which should've gotten it selected; instead VDF has selected everything else

![20230109-220514_VDF GUI](https://user-images.githubusercontent.com/99754576/211377124-c8b693cb-31d3-4647-ad30-8db11c7333e7.png)

All videos have the same duration, resolution and FPS. Only the red video has the lower bitrate; and it is the only video that was not selected.

NOTE: This issue is not present with only two duplicates of the same video.

**Expected behavior**
VDF selecting the lowest quality/duration video, irregardless of the duplicate group size.

**Comment by 0x90d** [comment] 2023-01-09 18:57
Can you share example videos so I can reproduce it on my end?

**Comment by ibintcd** [comment] 2023-01-10 17:10
Of course! [Here's the mega download link](https://mega.nz/folder/iIQ3QTqB#Eu4IxEHy1Gk6RmDfRq5nNw)

They all vary individually in resolution, FPS and bitrate respectively (although the latter is inconsistent).

I did some tests of my own; I believe there is some weird bug where VDF prioritizes the lowest bitrate duplicates for selection over the lower resolution IF the latter is outnumbered by the former. 

![20230110-205128_VDF GUI](https://user-images.githubusercontent.com/99754576/211613323-7f806fca-d556-4db1-87c5-b8004b6a35f6.png)

If the higher resolution video is outnumbered; it correctly selects the lower resolution duplicates.
![20230110-205356_VDF GUI](https://user-images.githubusercontent.com/99754576/211613858-beab1991-9aa4-4ace-8908-3bdd48e06579.png)


For some reason; I couldn't really reproduce the bug again in the original post where there is one single duplicate that is both low in resolution and bitrate outnumbered by higher quality ones, I think most likely the files I was dealing with originally had bad encoding or something.
![image](https://user-images.githubusercontent.com/99754576/211614245-6327e33b-7d8d-4d34-ae5e-de81d6eb98c8.png)
![image](https://user-images.githubusercontent.com/99754576/211614555-3cdbd588-0044-4810-a01a-8ac936f246fb.png)

**Comment by ibintcd** [comment] 2023-01-10 17:14
Of course! [Here's the mega download link](https://mega.nz/folder/iIQ3QTqB#Eu4IxEHy1Gk6RmDfRq5nNw)

They all vary individually in resolution, FPS and bitrate respectively (although the latter is inconsistent).

I did some tests of my own; I believe there is some weird bug where VDF prioritizes the lowest bitrate duplicates for selection over the lower resolution IF the latter is outnumbered by the former. 

![20230110-205128_VDF GUI](https://user-images.githubusercontent.com/99754576/211613323-7f806fca-d556-4db1-87c5-b8004b6a35f6.png)

If the higher resolution video is outnumbered; it correctly selects the lower resolution duplicates.
![20230110-205356_VDF GUI](https://user-images.githubusercontent.com/99754576/211613858-beab1991-9aa4-4ace-8908-3bdd48e06579.png)


For some reason; I couldn't really reproduce the bug again in the original post where there is one single duplicate that is both low in resolution and bitrate outnumbered by higher quality ones, I think most likely the files I was dealing with originally had bad encoding or something.
![image](https://user-images.githubusercontent.com/99754576/211614245-6327e33b-7d8d-4d34-ae5e-de81d6eb98c8.png)
![image](https://user-images.githubusercontent.com/99754576/211617995-feacb5bc-079b-4e21-829c-229da9c04302.png)

**Comment by 0x90d** [comment] 2023-01-19 11:38
Thank you for the files, I've downloaded them and get back to you when I've looked at them.

**Comment by 0x90d** [comment] 2023-01-20 08:40
I tried to reproduce it in various ways but I cannot:
![image](https://user-images.githubusercontent.com/46010672/213651674-cfd134a0-1088-43d9-9b47-67ed7ead0097.png)

In your last post the first screenshot shows that the unchecked item is for some reason marked as "IsBestBitrate". You can see the 7517 kbps is green. It should be red. This explains the selection and also means that the selection works as intended. Instead we have an issue on highlighting best matches. But from the code I cannot explain why this happens and I also cannot reproduce it either.

Are you using the latest version here from Github or did you build VDF yourself?

**Closed** 2023-01-31 07:55 UTC
Labels: bug, question
