### ISSUE TITLE
Too unstable

### ISSUE THREAD

**Issue by Shituation** [0x90d/videoduplicatefinder#307] opened 2022-03-12 17:15 UTC
**Environment**
 - OS: windows 10

sorry guys just writing to let you know the software is a good idea but its unusable right now. Its too unstable. It crashes all the time for no reason. Binding and unbinding ffmpeg doesnt make it work. So far this soft is good because its gui but too unstable. Having CTDs all the time mostly during or after scans. Cant keep recommending it on forums.

**Comment by 0x90d** [comment] 2022-03-12 17:27
If you have crashes, post details (crash log, how to reproduce etc). If you want to review VDF, feel free but not here. I'm closing this one because it has no constructive feedback.

**Closed by 0x90d** 2022-03-12 17:27 UTC

**Comment by Shituation** [comment] 2022-03-12 17:30
how to reproduce: use the software on windows 10. 
the log resets itself everytime.

**Comment by Shituation** [comment] 2022-03-12 17:33
https://github.com/0x90d/videoduplicatefinder/issues/297

**Comment by Shituation** [comment] 2022-03-12 17:35
https://github.com/0x90d/videoduplicatefinder/issues/293

**Comment by Shituation** [comment] 2022-03-12 17:36
https://github.com/0x90d/videoduplicatefinder/issues/256

**Comment by Shituation** [comment] 2022-03-12 17:40
Its always users fault.
