### ISSUE TITLE
About Multilingual Support

### ISSUE THREAD

**Issue by ssuyoungwu** [0x90d/videoduplicatefinder#499] opened 2024-04-10 12:08 UTC
This is a great project. Have you considered internationalization for your project - adding support for multiple languages?For example, Chinese, Korean, Japanese, French, German, etc.

**Comment by ssuyoungwu** [comment] 2024-04-10 12:12
If you want to add multilingual support, I can provide Chinese translation. However, as you know, the project needs to be modified to support multiple languages.
Hope you can reply, wish you a happy life.

**Comment by Soapland-JP** [comment] 2024-04-22 15:21
It would be even better if multi-language support could be added!

**Comment by 0x90d** [comment] 2024-04-27 09:00
Dupe of #497

**Closed by 0x90d** 2024-04-27 09:00 UTC
Labels: enhancement

**Comment by ssuyoungwu** [comment] 2024-04-27 14:22
Well,i think i understand your concern. I believe you can enlist the help of others to translate into different languages. You could put out a translation request in your "README.md" file for speakers of various languages, then use ChatGPT's translation to verify the results, ensuring they're generally accurate and don't carry unintended meanings.

In fact, I have already used Visual Studio 2022 and ChatGPT to translate your project into Chinese. I found that ChatGPT's translation results are not entirely accurate, and they need to be polished by someone who is proficient in the language.

And you, my friend, will have an increased workload. You'll need to modify the program to support multiple languages and take on the task of verifying the final translation results, which will make your job tougher. 

The God confounded the languages of the people at the Tower of Babel, preventing them from communicating with each other. But now, with the help of others and ChatGPT, we can make your program more functional and excellent. This, indeed, embodies the spirit and charm of open source, doesn't it?

![PixPin_2024-04-27_22-06-01](https://github.com/0x90d/videoduplicatefinder/assets/45707612/dc910b73-a4ef-4031-8de8-b821c743f6f4)

![PixPin_2024-04-27_22-06-09](https://github.com/0x90d/videoduplicatefinder/assets/45707612/3b92e263-f8c8-4276-9abb-6344d2cd4adb)

**Comment by lxwq** [comment] 2024-10-07 06:47
> This is a great project. Have you considered internationalization for your project - adding support for multiple languages?For example, Chinese, Korean, Japanese, French, German, etc.
这个汉化是如何做的？须修改哪些文件？编程小白一个，没一点基础，很多看不懂，目前只能编译运行一下，希望出个教程或直接做个中文版的，
