### ISSUE TITLE
advanced selection doesn't work.

### ISSUE THREAD

**Issue by masterofobzene** [0x90d/videoduplicatefinder#403] opened 2023-02-22 18:51 UTC
Environment

    OS: Windows 10 x64
# Using latest version downloaded today

Selection methods in "select custom" doesn't work.
The "path" option hangs the whole program.
The "select" button (to execute) doesn't do anything.

**Comment by 0x90d** [comment] 2023-02-22 18:55
> Selection methods in "select custom" doesn't work.

It does work

> The "path" option hangs the whole program.

Path option doesn't hang whole program.

> The "select" button (to execute) doesn't do anything.

It does

Provide more information means more information, not repeat yourself 3 times and enlarge the text. If that happens again I will also save time by just closing without comment.

**Comment by Maltragor** [comment] 2023-02-22 21:38
An IMHO comment:

Or you can look at it as there was no "release" since VDF 2.0.8. But in order to give users not able to build the Application themself the possibility to use it, the executable always automatically gets build based on the most current commit.

So of course when downloading the current version you know what you get.
There is the commit log: https://github.com/0x90d/videoduplicatefinder/commits/master and at least changes fixing an issue are marked accordingly. (And **if a issue is closed because of a fix** it always contains the link to this commit. In addition github sends a mail saying the issue is closed via commit xyz to the creator of the issue)
And to really ensure that the download contains a fix / change you can compare the timestamp on the right side of the download with the timestamp of the commit.
E.g. your #401was committed at Feb 22, 2023 6:41 PM and the download timestamp `(at the time this comment is written) `is Feb 22, 2023 6:42 / 6:43. So just about two minutes after the problem was fixed you can benefit from the fix. ... and don't need to wait days, weeks or month until one thinks.. oh, today is a good day to make a new release.

And if you download a version,... just keep it, write a readme containing the git has and some additional infos and don't delete it in case a newer version works worse in the meantime.

Of course I can understand that it would be nice if... 
...each modification is described in detail
...there would be an archive of older Executables 
...the Application would have an "version" identifier - in this case the git hash as there are no version ids
...automated UI tests and unit tests would be implemented to increase quality
...

But maybe you are interested to invest some of your free time to create a corresponding archive.
You could check the commit log regularly, decide if it is worth to archive the state as a new version, test the state extensively and then make the whole thing available to the general public as a release + change log.
Or do you have no time or desire to do so.
... but maybe others don't either^^.

**Closed** 2023-03-10 15:29 UTC
Labels: question

**Comment by 0x90d** [comment] 2023-03-10 15:32
About the off topic rent, I completely agree with every word of @Maltragor post.
