### ISSUE TITLE
Cannot select Mark as 'Not a match' on multiple groups

### ISSUE THREAD

**Issue by NixonUey** [0x90d/videoduplicatefinder#227] opened 2021-10-07 13:36 UTC
**Environment**
Windows 10

**Describe the bug**
Right-click on group then select Selected Group - Mark as 'Not a match' works the first time. If you try this on a second group the option Mark as 'Not a match' is grayed out and does not respond.

**Expected behavior**
Able to set multiple groups as not a match.

**Comment by 0x90d** [comment] 2021-10-10 06:12
I cannot reproduce this. For me the context menu item is always selectable.

**Comment by Maltragor** [comment] 2021-10-10 14:19
The interesting thing in the description is that the menu item is grayed out after the first click. As far as I know there is no code that does this (or did I miss something?), the only remaining cause would be that ReactiveCommand `MarkGroupAsNotAMatchCommand` gets stuck in an`await`. Because then the menu item is also grayed out. (Just tried with an `await Task.Delay(10000);`)

But I have no idea why `JsonSerializer.SerializeAsync()` would block here. Missing write permissions would already be detected by `FileStream` and VDF also stores various other data in `CoreUtils.CurrentFolder` where no problems seem to occur. And the `GroupBlacklist` as a simple string list also seems unproblematic to me with regard to JSON serialization.

**Comment by Maltragor** [comment] 2021-10-11 18:30
> just a user interface experience note here

That's why I had chosen the wording "Based on the implementation this is the expected behavior." and not just "expected behaviour" ;-)

As far as I know, it simply results from the fact that a right click in the used UI framework does not select the cell, but only a left click. _Whether the framework offers another way to get to the line in which the event took place, I can not answer you._

**Comment by 0x90d** [comment] 2021-10-12 11:56
> a right click in the used UI framework does not select the cell, but only a left click

This has been fixed, I've made a PR which got merged but I need to wait for new Avalonia version (their nightly build is broken). Still the original issue needs more information. Following the steps (Windows 10) it works as expected.

**Closed as completed** 2021-10-15 03:41 UTC
Labels: invalid
