### ISSUE TITLE
Crash on thumbnail generation using ffmpeg native binding

### ISSUE THREAD

**Issue by King555a** [0x90d/videoduplicatefinder#407] opened 2023-03-11 10:44 UTC
**Environment**
 - OS: Windows 10 22H2 x64

**Describe the bug**
When I started using VDF 3.x in September 2022, I did not have this problem. I did every update since then and since several updates, maybe it was one in the last 1 or 2 months, VDF crashes most of the times after a completed scan. There is absolutely no error message, not on the screen and not in the logs. I alread deleted everything including settings and database and did a new download and "install" of VDF. It still crashes. This is the log after the crash: 

    11:24:18 => Found previously scanned files, importing...
    11:24:18 => Previously scanned files imported. 36.104 files in 00:00:00.4412633
    11:24:38 => Files in database: 36.143 (39 files added)
    11:24:38 => Finished building file list in 00:00:20.8628825
    11:24:38 => Gathering media info and buildings hashes...
    [...]
    11:25:11 => Finished gathering and hashing in 00:00:32.3106845
    11:25:11 => Save scanned files to disk (36.143 files).
    11:25:11 => Scan for duplicates...
    11:25:11 => Prepare list of items to compare...
    11:25:11 => Scanning for duplicates in 36.060 files
    11:28:00 => Finished scanning for duplicates in 00:02:49.5157806
    11:28:00 => Highlighting best results...
    11:28:01 => Scan done.
    11:28:01 => Save scanned files to disk (36.143 files).

[...] are some ffmpeg error messages, because some files cannot be read correctly. But these error messages are there really every time, so I don't think they are related to the crash.

These are my settings:
![settings](https://user-images.githubusercontent.com/126968427/224479937-a2710cc9-4ea1-4495-8316-801c4a944775.png)

**Expected behavior**
No crash or at least an error message.

**Comment by 0x90d** [comment] 2023-03-11 10:47
There should be crash entries in the event viewer of Windows. Please take a look and post them here. Only the .NET crash entries are important.

Also try uncheck native ffmpeg binding and/or generate preview images to see if those matters.

**Comment by 0x90d** [comment] 2023-03-11 16:57
It IS the native binding + thumbnail generation. Which exact ffmpeg version you have?

**Comment by 0x90d** [comment] 2023-03-12 04:41
I cannot reproduce it with the given ffmpeg build. For some reason the exception is also not caught by my try-catch. It probably occurs within ffmpeg itself. Maybe caused by a corrupt video / frame, as you say it has worked before. Maybe @Maltragor has an idea how to deal with that?

**Comment by Maltragor** [comment] 2023-03-12 18:49
Then a few thoughts out loud:
It would certainly help to further narrow down the components involved in the error. 

- Are there certain videos that trigger the error _(of course, a video in that sense can't be the cause of the error, but it can trigger the error)._
If such a video would be identified, it would be easier to reproduce the error and search for the cause. 
> So there must be one quite new video on my harddisk, which does not want its thumbnails to be created.

- This is not necessarily the case. If a new video is recognized as a duplicate of an old one, this also leads to the creation of thumbnails of the old video. And if no thumbnails were created from the old one before, ... 
By the way, thumbnails are also created once during the scan of new videos. But then in a different resolution and only in grayscale.
You write that you have deleted the database before. So if there is a particular video that triggers the error, then it only happens with the larger thumbnails displayed. A smaller grayscale thumbnail would have already been successfully created in that case.
To find out without adjustments to VDF if a certain video causes problems and if so which one, you could use "Process Monitor" (https://learn.microsoft.com/en-us/sysinternals/downloads/procmon). The program records among other things all file accesses. The last video file accessed before VDF crashes would be the one you are looking for, especially if it is always the same.
A few more notes about this: VDF can process multiple files at the same time. (Settings: Max Degree Of Parallelism > 1). In this case the last one in the log is not necessarily the one you are looking for. Therefore set "Max Degree Of Parallelism" to 1.
On the other hand you have to get familiar with the functionality of Process Monitor. (Set filter of the processes to be monitored, disable registry monitoring,... otherwise the log will be very full)

_(@0x90d In principle, you could also think about whether VDF (configurable) also logs the access before each thumbnail creation and outputs it together with the normal log via System.Diagnostics.Trace.WriteLine(), so that you can still read everything even in case of a crash)._
- If "Hardware Acceleration" is active in the VDF settings, I would also disable it for a test.

- On https://ffmpeg.org/download.html there are two links for Windows. The second one (https://github.com/BtbN/FFmpeg-Builds/releases) still has the older ffmpeg versions, so you could try different versions.

- @0x90d VDF uses another library (FFmpeg.AutoGen) for native ffmpeg access. On 2023-02-06 there was a commit in VDF to update this from 5.0.0 to 5.1.1.
  Since this is in the 1-2 month timeframe mentioned, this would also be a possible candidate. 

`Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`

> For some reason the exception is also not caught by my try-catch.

@0x90d Well, the error message sounds a bit special. I have briefly researched:  
https://learn.microsoft.com/en-us/dotnet/api/system.accessviolationexception?view=net-7.0
> [AccessViolationException](https://learn.microsoft.com/en-us/dotnet/api/system.accessviolationexception?view=net-7.0) exceptions thrown by the common language runtime are not handled by the catch statement in a structured exception handler if the exception occurs outside of the memory reserved by the common language runtime. To handle such an [AccessViolationException](https://learn.microsoft.com/en-us/dotnet/api/system.accessviolationexception?view=net-7.0) exception, apply the [HandleProcessCorruptedStateExceptionsAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.exceptionservices.handleprocesscorruptedstateexceptionsattribute?view=net-7.0) attribute to the method

**Comment by 0x90d** [comment] 2023-03-13 10:10
> Well, the error message sounds a bit special. I have briefly researched:

I cannot apply this attribute as a red box on MDSN says that for .NET 7 this attribute is ignored. Extended logging is something I definitely consider, possibly by switching to SeriLog or similar.

@King555a: Running a ffmpeg command wouldn't necessarily help as ffmpeg.exe seems to handle it fine (you say that disabling native binding does not crash, I expect you have let it complete thumbnail generation at least once?). As a workaround you could possibly convert this video file using a different codec. I'm currently seeing myself unable to fix it. I cannot catch/handle this exception and it seems to occur either in Ffmpeg.AutoGen or in ffmpeg. In first case I could only up-/ or downgrade. Have you tried a different ffmpeg version yourself?

**Comment by Maltragor** [comment] 2023-03-13 20:57
> And the file is not new, but several years old.

Is this old video recognized as a duplicate of a new video? So does the error occur since the mentioned one to two months because in that time a corresponding new similar video was added to the collection, or is it really due to a software update?

**Comment by 0x90d** [comment] 2024-06-15 05:26
I'm closing this as I don't think it's something I could fix on my end. And perhaps it's not even relevant anymore.

**Closed by 0x90d** 2024-06-15 05:26 UTC
Labels: bug, external-issue

**Comment by Rootkit-** [comment] 2025-01-10 09:38
Not to bump, just to let you know, if I'm correct I found that this happens when its creating the thumbnails and you try to do something, like delete/select. Before it saves/enumerates you just got to wait for it to finish creating thumbnails before you start trying to delete. Not entirely certain, but, just incase someone else brings it up that might help you ferret out the error.

Shared ffmpeg, hw accel none.
