### ISSUE TITLE
What other way to accurately detect the worst file to remove?

### ISSUE THREAD

**Issue by Disorbs** [0x90d/videoduplicatefinder#314] opened 2022-05-28 09:39 UTC
**Environment**
- Windows

**Describe the bug**
- I Choose (Select lowest duration/quality) and it picks the good file to remove for some reason when a 1080p file over a 720p badly compressed file.

**Expected behavior**
- I want it to choose the good option (1080p) instead of the 720p 30fps where sometimes the mb is bigger and chooses it over the good one.

**Example:**
- ![choose to remove the good file](https://user-images.githubusercontent.com/10566466/170819715-ea78096a-4fff-4aba-a8a4-9c8450134ab5.png)

Is there a custom filter where it would make sure to choose the bad quality one instead of the good option just because it has a higher fps/mb?

**Comment by rezad1393** [comment] 2022-06-06 10:17
I dont recommend using automated way to remove files.
this app finds simalar files but it has false positives, which means it may find files that are not related, as duplicate. 
I have seen it with animation a lot.

also selecting better version of movies is a subjective task and also sometimes the video files are not encoded from the same source.
for example this app is smart enough to find in my movies a duplicate of a video that was a vhs rip and another one that was tv-rip.
I had to personally compare them to decide what to do with them.

not every video duplicate is 720p and 1080p version sources from same Blueray and encoded by same group.

**Comment by 0x90d** [comment] 2022-06-10 07:30
Resolution is not always better. You can have a 4k video with 10 FPS and 100kbps which is worser than 720p with 30 FPS and 5,000kbps.

The pre selection should only be used as a helper. Like @rezad1393 said you then have to go through the list and verify/correct it. For your own logic you can also use the expression builder.

**Closed by 0x90d** 2022-06-10 07:30 UTC
