### ISSUE TITLE
Group of "one"

### ISSUE THREAD

**Issue by yami-no-tusbas** [0x90d/videoduplicatefinder#171] opened 2021-08-19 06:47 UTC
**Environment**
 - Windows 11

**Describe the bug**
Sometimes your app just send a group of "one" duplicate, this make no sense.
![Lm9VPdz0Pd](https://user-images.githubusercontent.com/3921598/130021029-3ecaf8af-b785-4f2d-928e-d6dc8b2c3f7b.png)

**Expected behavior**
Skip thoses groups and don't show them to the end user.

**Comment by 0x90d** [comment] 2021-08-19 08:20
Did you any action to duplicates before (removing, copying, etc.)? If not, provide me an example video where this happens as I cannot reproduce it.

**Comment by Maltragor** [comment] 2021-08-19 20:45
This also happened to me occasionally in VDF 2.
At least there I could not assign it to a video and it occurred only rarely and not reproducibly.
My assumption at that time was that it could be a synchronization problem (of the concurrent comparisons), or that an actually existing table entry is not displayed for whatever reason.

So the statement is, that I don't know what the problem is^^.
But if the behavior does not occur again after a restart of VDF and a new scan with unchanged parameters, then it probably has nothing to do with the videos and it is something that already existed in the previous version.

**Comment by yami-no-tusbas** [comment] 2021-08-21 11:02
> 
> 
> Did you any action to duplicates before (removing, copying, etc.)? If not, provide me an example video where this happens as I cannot reproduce it.

What I usualy do, is start at 99%, then i use the software to remove to bin the files, then, lower the percentage, start again, could it be the process keep in memory some deleted files ? I'll try reproduce it from the start.
Started the program, selected a folder with some vids to make it faster. No result à 99, go down to 68%, will get lot of false positives, but it is not relevent here. Found some "groups of one", closed the app, restarted with the same setting 68% one folder and some sub folder. Found the same "groups of one" : 
![image](https://user-images.githubusercontent.com/3921598/130319691-705b91de-5654-4791-be41-e8365a6336f6.png)

Theses are pretty big files, but it can happen to any file as far as I know. And there is the logs, but nothin crazy here.
[logs..txt](https://github.com/0x90d/videoduplicatefinder/files/7025369/logs.txt)

**Comment by 0x90d** [comment] 2021-09-03 12:45
I've added your file to my duplicate test folder and taken your settings but I don't see your file as a duplicate in my list at all. When this happens again please export your scan results (which I've added recently) and upload it here. Or just verify yourself that there is also a group with a single item only. Maybe this is just a visual bug of Avalonia?

**Comment by Maltragor** [comment] 2021-09-11 20:29
After I also had a setting where some "group of one" occurred reproducibly, I looked for the error.
Since it is only a small thing, I have not created an extra PR, but still it is a nasty bug when merging the groupIDs.

https://github.com/0x90d/videoduplicatefinder/blob/b28a9027b0cb06c400b0217bef94bf4cf8b21116/VDF.Core/ScanEngine.cs#L267-L275

The `existingComp.GroupId` value in `Where(c => c.GroupId == existingComp.GroupId)` will change while the loop is running because the loop replaces all Comp.GroupIds by Base.GroupId.
So "group of one" is only a conspicuous special case of the merge bug.

Bugfix:
Store `existingComp.GroupId` in an additional variable and use this variable inside `Where(...) `

**Comment by Maltragor** [comment] 2021-09-11 21:22
_Could it be that it is currently no longer possible to create new issues? The "Submit new issue" button is disabled and always stays pale green._

**Comment by 0x90d** [comment] 2021-09-13 05:48
> _Could it be that it is currently no longer possible to create new issues? The "Submit new issue" button is disabled and always stays pale green._

_I didn't changed anything. For me this button is still green._

**Closed** 2021-09-13 06:10 UTC
Labels: question
